// Mocks generated by Mockito 5.4.4 from annotations
// in phoenix_socket/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:phoenix_socket/src/channel.dart' as _i5;
import 'package:phoenix_socket/src/events.dart' as _i8;
import 'package:phoenix_socket/src/exceptions.dart' as _i9;
import 'package:phoenix_socket/src/message.dart' as _i3;
import 'package:phoenix_socket/src/push.dart' as _i4;
import 'package:phoenix_socket/src/socket.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePhoenixSocket_0 extends _i1.SmartFake implements _i2.PhoenixSocket {
  _FakePhoenixSocket_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessage_1 extends _i1.SmartFake implements _i3.Message {
  _FakeMessage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePush_2 extends _i1.SmartFake implements _i4.Push {
  _FakePush_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_4 extends _i1.SmartFake implements Uri {
  _FakeUri_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhoenixChannel_5 extends _i1.SmartFake
    implements _i5.PhoenixChannel {
  _FakePhoenixChannel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PhoenixChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhoenixChannel extends _i1.Mock implements _i5.PhoenixChannel {
  @override
  Map<String, dynamic> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.PhoenixSocket get socket => (super.noSuchMethod(
        Invocation.getter(#socket),
        returnValue: _FakePhoenixSocket_0(
          this,
          Invocation.getter(#socket),
        ),
        returnValueForMissingStub: _FakePhoenixSocket_0(
          this,
          Invocation.getter(#socket),
        ),
      ) as _i2.PhoenixSocket);

  @override
  String get topic => (super.noSuchMethod(
        Invocation.getter(#topic),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#topic),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#topic),
        ),
      ) as String);

  @override
  List<_i4.Push> get pushBuffer => (super.noSuchMethod(
        Invocation.getter(#pushBuffer),
        returnValue: <_i4.Push>[],
        returnValueForMissingStub: <_i4.Push>[],
      ) as List<_i4.Push>);

  @override
  _i7.Stream<_i3.Message> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _i7.Stream<_i3.Message>.empty(),
        returnValueForMissingStub: _i7.Stream<_i3.Message>.empty(),
      ) as _i7.Stream<_i3.Message>);

  @override
  String get joinRef => (super.noSuchMethod(
        Invocation.getter(#joinRef),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#joinRef),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#joinRef),
        ),
      ) as String);

  @override
  _i5.PhoenixChannelState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.PhoenixChannelState.closed,
        returnValueForMissingStub: _i5.PhoenixChannelState.closed,
      ) as _i5.PhoenixChannelState);

  @override
  bool get canPush => (super.noSuchMethod(
        Invocation.getter(#canPush),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get loggerName => (super.noSuchMethod(
        Invocation.getter(#loggerName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#loggerName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#loggerName),
        ),
      ) as String);

  @override
  String get reference => (super.noSuchMethod(
        Invocation.getter(#reference),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#reference),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#reference),
        ),
      ) as String);

  @override
  _i7.Future<_i3.Message> onPushReply(_i8.PhoenixChannelEvent? replyEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPushReply,
          [replyEvent],
        ),
        returnValue: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #onPushReply,
            [replyEvent],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #onPushReply,
            [replyEvent],
          ),
        )),
      ) as _i7.Future<_i3.Message>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trigger(_i3.Message? message) => super.noSuchMethod(
        Invocation.method(
          #trigger,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerError(_i9.PhoenixException? error) => super.noSuchMethod(
        Invocation.method(
          #triggerError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Push leave({Duration? timeout}) => (super.noSuchMethod(
        Invocation.method(
          #leave,
          [],
          {#timeout: timeout},
        ),
        returnValue: _FakePush_2(
          this,
          Invocation.method(
            #leave,
            [],
            {#timeout: timeout},
          ),
        ),
        returnValueForMissingStub: _FakePush_2(
          this,
          Invocation.method(
            #leave,
            [],
            {#timeout: timeout},
          ),
        ),
      ) as _i4.Push);

  @override
  _i4.Push join([Duration? newTimeout]) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [newTimeout],
        ),
        returnValue: _FakePush_2(
          this,
          Invocation.method(
            #join,
            [newTimeout],
          ),
        ),
        returnValueForMissingStub: _FakePush_2(
          this,
          Invocation.method(
            #join,
            [newTimeout],
          ),
        ),
      ) as _i4.Push);

  @override
  _i4.Push push(
    String? eventName,
    Map<String, dynamic>? payload, [
    Duration? newTimeout,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [
            eventName,
            payload,
            newTimeout,
          ],
        ),
        returnValue: _FakePush_2(
          this,
          Invocation.method(
            #push,
            [
              eventName,
              payload,
              newTimeout,
            ],
          ),
        ),
        returnValueForMissingStub: _FakePush_2(
          this,
          Invocation.method(
            #push,
            [
              eventName,
              payload,
              newTimeout,
            ],
          ),
        ),
      ) as _i4.Push);

  @override
  _i4.Push pushEvent(
    _i8.PhoenixChannelEvent? event,
    Map<String, dynamic>? payload, [
    Duration? newTimeout,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushEvent,
          [
            event,
            payload,
            newTimeout,
          ],
        ),
        returnValue: _FakePush_2(
          this,
          Invocation.method(
            #pushEvent,
            [
              event,
              payload,
              newTimeout,
            ],
          ),
        ),
        returnValueForMissingStub: _FakePush_2(
          this,
          Invocation.method(
            #pushEvent,
            [
              event,
              payload,
              newTimeout,
            ],
          ),
        ),
      ) as _i4.Push);
}

/// A class which mocks [PhoenixSocket].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhoenixSocket extends _i1.Mock implements _i2.PhoenixSocket {
  @override
  Map<String, _i5.PhoenixChannel> get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: <String, _i5.PhoenixChannel>{},
        returnValueForMissingStub: <String, _i5.PhoenixChannel>{},
      ) as Map<String, _i5.PhoenixChannel>);

  @override
  set channels(Map<String, _i5.PhoenixChannel>? _channels) =>
      super.noSuchMethod(
        Invocation.setter(
          #channels,
          _channels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<_i8.PhoenixSocketOpenEvent> get openStream => (super.noSuchMethod(
        Invocation.getter(#openStream),
        returnValue: _i7.Stream<_i8.PhoenixSocketOpenEvent>.empty(),
        returnValueForMissingStub:
            _i7.Stream<_i8.PhoenixSocketOpenEvent>.empty(),
      ) as _i7.Stream<_i8.PhoenixSocketOpenEvent>);

  @override
  _i7.Stream<_i8.PhoenixSocketCloseEvent> get closeStream =>
      (super.noSuchMethod(
        Invocation.getter(#closeStream),
        returnValue: _i7.Stream<_i8.PhoenixSocketCloseEvent>.empty(),
        returnValueForMissingStub:
            _i7.Stream<_i8.PhoenixSocketCloseEvent>.empty(),
      ) as _i7.Stream<_i8.PhoenixSocketCloseEvent>);

  @override
  _i7.Stream<_i8.PhoenixSocketErrorEvent> get errorStream =>
      (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i7.Stream<_i8.PhoenixSocketErrorEvent>.empty(),
        returnValueForMissingStub:
            _i7.Stream<_i8.PhoenixSocketErrorEvent>.empty(),
      ) as _i7.Stream<_i8.PhoenixSocketErrorEvent>);

  @override
  _i7.Stream<_i3.Message> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i7.Stream<_i3.Message>.empty(),
        returnValueForMissingStub: _i7.Stream<_i3.Message>.empty(),
      ) as _i7.Stream<_i3.Message>);

  @override
  String get nextRef => (super.noSuchMethod(
        Invocation.getter(#nextRef),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#nextRef),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#nextRef),
        ),
      ) as String);

  @override
  Duration get defaultTimeout => (super.noSuchMethod(
        Invocation.getter(#defaultTimeout),
        returnValue: _FakeDuration_3(
          this,
          Invocation.getter(#defaultTimeout),
        ),
        returnValueForMissingStub: _FakeDuration_3(
          this,
          Invocation.getter(#defaultTimeout),
        ),
      ) as Duration);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  Uri get mountPoint => (super.noSuchMethod(
        Invocation.getter(#mountPoint),
        returnValue: _FakeUri_4(
          this,
          Invocation.getter(#mountPoint),
        ),
        returnValueForMissingStub: _FakeUri_4(
          this,
          Invocation.getter(#mountPoint),
        ),
      ) as Uri);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Stream<_i3.Message> streamForTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #streamForTopic,
          [topic],
        ),
        returnValue: _i7.Stream<_i3.Message>.empty(),
        returnValueForMissingStub: _i7.Stream<_i3.Message>.empty(),
      ) as _i7.Stream<_i3.Message>);

  @override
  _i7.Future<_i2.PhoenixSocket?> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i7.Future<_i2.PhoenixSocket?>.value(),
        returnValueForMissingStub: _i7.Future<_i2.PhoenixSocket?>.value(),
      ) as _i7.Future<_i2.PhoenixSocket?>);

  @override
  void close([
    int? code,
    String? reason,
    dynamic reconnect = false,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #close,
          [
            code,
            reason,
            reconnect,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.Message> waitForMessage(_i3.Message? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #waitForMessage,
          [message],
        ),
        returnValue: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #waitForMessage,
            [message],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #waitForMessage,
            [message],
          ),
        )),
      ) as _i7.Future<_i3.Message>);

  @override
  _i7.Future<_i3.Message> sendMessage(_i3.Message? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #sendMessage,
            [message],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Message>.value(_FakeMessage_1(
          this,
          Invocation.method(
            #sendMessage,
            [message],
          ),
        )),
      ) as _i7.Future<_i3.Message>);

  @override
  _i5.PhoenixChannel addChannel({
    required String? topic,
    Map<String, dynamic>? parameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addChannel,
          [],
          {
            #topic: topic,
            #parameters: parameters,
            #timeout: timeout,
          },
        ),
        returnValue: _FakePhoenixChannel_5(
          this,
          Invocation.method(
            #addChannel,
            [],
            {
              #topic: topic,
              #parameters: parameters,
              #timeout: timeout,
            },
          ),
        ),
        returnValueForMissingStub: _FakePhoenixChannel_5(
          this,
          Invocation.method(
            #addChannel,
            [],
            {
              #topic: topic,
              #parameters: parameters,
              #timeout: timeout,
            },
          ),
        ),
      ) as _i5.PhoenixChannel);

  @override
  void removeChannel(_i5.PhoenixChannel? channel) => super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValueForMissingStub: null,
      );
}
