// Generated by tool/long_poll_reference.mjs from Phoenix v1.8.15.
// Do not edit expectations manually.
const phoenixLongPollReferenceJson = r'''
{
  "version": "1.8.15",
  "commit": "bd1801833b4fd7ceb02497cc7ba2d05e9bd391c8",
  "endpoints": [
    {
      "input": "wss://example.invalid/socket/websocket?vsn=2.0.0",
      "expected": "https://example.invalid/socket/longpoll?vsn=2.0.0"
    },
    {
      "input": "ws://localhost/socket/websocket",
      "expected": "http://localhost/socket/longpoll"
    },
    {
      "input": "https://example.invalid/socket/longpoll?x=1",
      "expected": "https://example.invalid/socket/longpoll?x=1"
    },
    {
      "input": "wss://example.invalid/a/websocket/socket/websocket?x=1",
      "expected": "https://example.invalid/a/websocket/socket/longpoll?x=1"
    }
  ],
  "poll": [
    {
      "status": 403,
      "events": [
        [
          "error",
          403
        ],
        [
          "close",
          1008,
          "forbidden"
        ]
      ]
    },
    {
      "status": 500,
      "events": [
        [
          "error",
          500
        ],
        [
          "close",
          1011,
          "internal server error"
        ]
      ]
    },
    {
      "status": 0,
      "events": [
        [
          "error",
          500
        ],
        [
          "close",
          1011,
          "internal server error"
        ]
      ]
    },
    {
      "status": 410,
      "events": [
        [
          "open"
        ],
        [
          "error",
          410
        ],
        [
          "close",
          3410,
          "session_gone"
        ]
      ]
    }
  ],
  "batches": {
    "requests": [
      {
        "method": "POST",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=t",
        "headers": {
          "Content-Type": "application/x-ndjson"
        },
        "body": "m0\nm1\nm2\nm3\nm4\nm5\nm6\nm7\nm8\nm9\nm10\nm11\nm12\nm13\nm14\nm15\nm16\nm17\nm18\nm19\nm20\nm21\nm22\nm23\nm24\nm25\nm26\nm27\nm28\nm29\nm30\nm31\nm32\nm33\nm34\nm35\nm36\nm37\nm38\nm39\nm40\nm41\nm42\nm43\nm44\nm45\nm46\nm47\nm48\nm49\nm50\nm51\nm52\nm53\nm54\nm55\nm56\nm57\nm58\nm59\nm60\nm61\nm62\nm63\nm64\nm65\nm66\nm67\nm68\nm69\nm70\nm71\nm72\nm73\nm74\nm75\nm76\nm77\nm78\nm79\nm80\nm81\nm82\nm83\nm84\nm85\nm86\nm87\nm88\nm89\nm90\nm91\nm92\nm93\nm94\nm95\nm96\nm97\nm98\nm99"
      },
      {
        "method": "POST",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=t",
        "headers": {
          "Content-Type": "application/x-ndjson"
        },
        "body": "m100\nm101\nm102\nm103\nm104\nm105\nm106\nm107\nm108\nm109\nm110\nm111\nm112\nm113\nm114\nm115\nm116\nm117\nm118\nm119\nm120\nm121\nm122\nm123\nm124\nm125\nm126\nm127\nm128\nm129\nm130\nm131\nm132\nm133\nm134\nm135\nm136\nm137\nm138\nm139\nm140\nm141\nm142\nm143\nm144\nm145\nm146\nm147\nm148\nm149\nm150\nm151\nm152\nm153\nm154\nm155\nm156\nm157\nm158\nm159\nm160\nm161\nm162\nm163\nm164\nm165\nm166\nm167\nm168\nm169\nm170\nm171\nm172\nm173\nm174\nm175\nm176\nm177\nm178\nm179\nm180\nm181\nm182\nm183\nm184\nm185\nm186\nm187\nm188\nm189\nm190\nm191\nm192\nm193\nm194\nm195\nm196\nm197\nm198\nm199"
      },
      {
        "method": "POST",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=t",
        "headers": {
          "Content-Type": "application/x-ndjson"
        },
        "body": "m200\nm201\nm202\nm203\nm204\nm205\nm206\nm207\nm208\nm209\nm210\nm211\nm212\nm213\nm214\nm215\nm216\nm217\nm218\nm219\nm220\nm221\nm222\nm223\nm224\nm225\nm226\nm227\nm228\nm229\nm230\nm231\nm232\nm233\nm234\nm235\nm236\nm237\nm238\nm239\nm240\nm241\nm242\nm243\nm244\nm245\nm246\nm247\nm248\nm249"
      },
      {
        "method": "POST",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=t",
        "headers": {
          "Content-Type": "application/x-ndjson"
        },
        "body": "buffered"
      }
    ]
  },
  "session": {
    "requests": [
      {
        "method": "GET",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&",
        "headers": {
          "Accept": "application/json",
          "X-Phoenix-AuthToken": "reference-token"
        },
        "body": null
      },
      {
        "method": "GET",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=session%20%2B%2F%3D%26",
        "headers": {
          "Accept": "application/json",
          "X-Phoenix-AuthToken": "reference-token"
        },
        "body": null
      },
      {
        "method": "GET",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=session%20%2B%2F%3D%26",
        "headers": {
          "Accept": "application/json",
          "X-Phoenix-AuthToken": "reference-token"
        },
        "body": null
      },
      {
        "method": "GET",
        "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=session%20%2B%2F%3D%26",
        "headers": {
          "Accept": "application/json",
          "X-Phoenix-AuthToken": "reference-token"
        },
        "body": null
      }
    ],
    "events": [
      [
        "open"
      ],
      [
        "message",
        "a"
      ],
      [
        "message",
        "b"
      ],
      [
        "message",
        "c"
      ]
    ]
  },
  "binary": {
    "method": "POST",
    "url": "https://example.invalid/socket/longpoll?vsn=2.0.0&token=t",
    "headers": {
      "Content-Type": "application/x-ndjson"
    },
    "body": "AID/\n[null,\"0\",\"audit\",\"echo\",{\"unicode\":\"é🐦\"}]"
  },
  "timeout": [
    [
      "open"
    ],
    [
      "error",
      "timeout"
    ],
    [
      "close",
      1005,
      "timeout"
    ]
  ]
}
''';
