name: ci-test

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/test.yaml"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      backend:
        image: braverhq/phoenix-dart-server
        ports:
          - 4001:4001
          - 4002:4002
        
      proxy:
        image: ghcr.io/shopify/toxiproxy
        ports:
          - 8474:8474
          - 4004:4004

    steps:

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          architecture: x64
          sdk: "3.1.2"

      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Fetch dependencies
        run: dart pub get

      - name: Run analysis
        run: |
          dart analyze --fatal-infos lib/
          dart analyze test/

      - name: Run tests
        run: dart run test
