// Generated by tool/generate_wire_vectors.py; do not hand-edit.
const independentWireVectorsJson = r'''
{
  "producer": {
    "phoenix": "https://raw.githubusercontent.com/phoenixframework/phoenix/v1.8.14/assets/js/phoenix/serializer.js",
    "phoenix_sha256": "37f7911efdae9c699c2de7380f268e2a7fac24e27d39afdd0e4764a90356ffd4",
    "msgpack": "1.2.3",
    "protobuf": "6.33.6"
  },
  "phoenix": {
    "clients": [
      {
        "name": "ordinary",
        "join_ref": "1",
        "ref": "2",
        "topic": "room",
        "event": "echo",
        "bytes": [
          0,
          128,
          255
        ],
        "frame": "00010104043132726f6f6d6563686f0080ff"
      },
      {
        "name": "unicode",
        "join_ref": "",
        "ref": "",
        "topic": "røom🙂",
        "event": "更新",
        "bytes": [
          1,
          2
        ],
        "frame": "000000090672c3b86f6df09f9982e69bb4e696b00102"
      },
      {
        "name": "empty",
        "join_ref": "",
        "ref": "",
        "topic": "room",
        "event": "empty",
        "bytes": [],
        "frame": "0000000405726f6f6d656d707479"
      },
      {
        "name": "metadata-limit",
        "join_ref": "1",
        "ref": "2",
        "topic": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "event": "echo",
        "bytes": [
          42
        ],
        "frame": "000101ff0431327878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878786563686f2a"
      }
    ],
    "servers": [
      {
        "name": "push",
        "frame": "000109063172c3b86f6df09f9982e69bb4e696b00080ff",
        "message": {
          "join_ref": "1",
          "ref": null,
          "topic": "røom🙂",
          "event": "更新",
          "payload": {
            "$bytes": "0080ff"
          }
        }
      },
      {
        "name": "reply",
        "frame": "01010104053132726f6f6d6572726f720080ff",
        "message": {
          "join_ref": "1",
          "ref": "2",
          "topic": "room",
          "event": "phx_reply",
          "payload": {
            "status": "error",
            "response": {
              "$bytes": "0080ff"
            }
          }
        }
      },
      {
        "name": "broadcast",
        "frame": "020406726f6f6d7570646174650080ff",
        "message": {
          "join_ref": null,
          "ref": null,
          "topic": "room",
          "event": "update",
          "payload": {
            "$bytes": "0080ff"
          }
        }
      },
      {
        "name": "empty",
        "frame": "020000",
        "message": {
          "join_ref": null,
          "ref": null,
          "topic": "",
          "event": "",
          "payload": {
            "$bytes": ""
          }
        }
      }
    ]
  },
  "messagepack": [
    {
      "name": "nested",
      "frame": "95c0a132a572c3b86f6da56576656e7482a56974656d7394c0c3c281a474657874aa68c3a96c6c6ff09f9982a56279746573c4030080ff",
      "message": [
        null,
        "2",
        "røom",
        "event",
        {
          "items": [
            null,
            true,
            false,
            {
              "text": "héllo🙂"
            }
          ],
          "bytes": {
            "$bytes": "0080ff"
          }
        }
      ]
    },
    {
      "name": "numbers",
      "frame": "95c0a132a572c3b86f6da56576656e7481a676616c7565739ad2ffff7fffd1ff7fd0dfff007fcc80cd0100ce00010000cb400a000000000000",
      "message": [
        null,
        "2",
        "røom",
        "event",
        {
          "values": [
            -32769,
            -129,
            -33,
            -1,
            0,
            127,
            128,
            256,
            65536,
            3.25
          ]
        }
      ]
    },
    {
      "name": "str32",
      "frame": "95c0a132a572c3b86f6da56576656e7481a474657874d9207878787878787878787878787878787878787878787878787878787878787878",
      "message": [
        null,
        "2",
        "røom",
        "event",
        {
          "text": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
      ]
    },
    {
      "name": "array16",
      "frame": "95c0a132a572c3b86f6da56576656e74dc0010000102030405060708090a0b0c0d0e0f",
      "message": [
        null,
        "2",
        "røom",
        "event",
        [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ]
      ]
    },
    {
      "name": "binary256",
      "frame": "95c0a132a572c3b86f6da56576656e74c50100000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
      "message": [
        null,
        "2",
        "røom",
        "event",
        {
          "$bytes": "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"
        }
      ]
    },
    {
      "name": "empty-binary",
      "frame": "95c0a132a572c3b86f6da56576656e74c400",
      "message": [
        null,
        "2",
        "røom",
        "event",
        {
          "$bytes": ""
        }
      ]
    },
    {
      "name": "reply",
      "frame": "95c0a132a572c3b86f6da97068785f7265706c7982a6737461747573a56572726f72a8726573706f6e7365c40200ff",
      "message": [
        null,
        "2",
        "røom",
        "phx_reply",
        {
          "status": "error",
          "response": {
            "$bytes": "00ff"
          }
        }
      ]
    }
  ],
  "protobuf": [
    {
      "name": "Reply-empty",
      "schema": "Reply",
      "value": "",
      "frame": ""
    },
    {
      "name": "Reply-unicode",
      "schema": "Reply",
      "value": "héllo🙂",
      "frame": "0a0a68c3a96c6c6ff09f9982"
    },
    {
      "name": "Reply-escaped",
      "schema": "Reply",
      "value": "quote\"\\\n\u0000",
      "frame": "0a0971756f7465225c0a00"
    },
    {
      "name": "Reply-long",
      "schema": "Reply",
      "value": "λλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλ",
      "frame": "0a8c01cebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebb"
    },
    {
      "name": "Reply-unknown",
      "schema": "Reply",
      "value": "unknown preserved",
      "frame": "0a11756e6b6e6f776e20707265736572766564f807c10d"
    },
    {
      "name": "Update-empty",
      "schema": "Update",
      "value": "",
      "frame": ""
    },
    {
      "name": "Update-unicode",
      "schema": "Update",
      "value": "héllo🙂",
      "frame": "120a68c3a96c6c6ff09f9982"
    },
    {
      "name": "Update-escaped",
      "schema": "Update",
      "value": "quote\"\\\n\u0000",
      "frame": "120971756f7465225c0a00"
    },
    {
      "name": "Update-long",
      "schema": "Update",
      "value": "λλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλ",
      "frame": "128c01cebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebbcebb"
    },
    {
      "name": "Update-unknown",
      "schema": "Update",
      "value": "unknown preserved",
      "frame": "1211756e6b6e6f776e20707265736572766564f807c10d"
    }
  ]
}
''';
